services:
  mongo:
    image: mongo:8.0
    environment:
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./backend/src/uploads:/app/src/uploads
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: